<?php

use Illuminate\Database\Seeder;
use App\StaticContent;

class StaticContentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('static_contents')->delete();
        StaticContent::create(['page' => 'Home Page',  'item' => 'Top Picture', 'type' => 'image',
            'content' => 'http://i.imgur.com/B9J0WSl.jpg', 'default_content' => 'images/rochester2016.jpg', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Top Description Box', 'type' => 'text',
            'content' => 'Junior Achievement\'s volunteer-delivered, kindergarten-12th grade programs foster work-readiness, entrepreneurshipand financial literacy skills, and use experiential learning to inspire students to dream big and reach their potential.', 'default_content' => 'Junior Achievement\'s volunteer-delivered, kindergarten-12th grade programs foster work-readiness, entrepreneurship and financial literacy skills, and use experiential learning to inspire students to dream big and reach their potential.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Why JA? Description', 'type' => 'text',
            'content' => 'Junior Achievement helps students realize that the education they are getting today will help them to have a bright future tomorrow. Junior Achievement\'s unique, volunteer delivered programs, show them all of the possibilities that lay before them. They realize they can choose different paths; College? A specific trade? Start their own business? Through your participation as an organization or as an individual, these statistics below can begin to change in your community:', 'default_content' => 'Junior Achievement helps students realize that the education they are getting today will help them to have a bright future tomorrow. Junior Achievement\'s unique, volunteer delivered programs, show them all of the possibilities that lay before them. They realize they can choose different paths; College? A specific trade? Start their own business? Through your participation as an organization or as an individual, these statistics below can begin to change in your community:', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Why JA? Picture', 'type' => 'image',
            'content' => 'images/two-cols-classroom_sm.jpg', 'default_content' => 'images/two-cols-classroom_sm.jpg', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Why JA? Fact 1', 'type' => 'text',
            'content' => '20% of U.S. students will not complete high school on time and earn a diploma.', 'default_content' => '20% of U.S. students will not complete high school on time and earn a diploma.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Why JA? Fact 2', 'type' => 'text',
            'content' => '49% of U.S. employers recognize that talent shortages impact their ability to serve clients and customers.', 'default_content' => '49% of U.S. employers recognize that talent shortages impact their ability to serve clients and customers.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Why JA? Fact 3', 'type' => 'text',
            'content' => '36% of Americans say that they have at some point in their lives felt their financial situation was out of control.', 'default_content' => '36% of Americans say that they have at some point in their lives felt their financial situation was out of control.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Why JA? Fact 4', 'type' => 'text',
            'content' => '91% of millennials wish they had greater access to entrepreneurial education programs.', 'default_content' => '91% of millennials wish they had greater access to entrepreneurial education programs.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);
        StaticContent::create(['page' => 'Home Page',  'item' => 'Video', 'type' => 'text',
            'content' => 'https://www.youtube.com/embed/4L49IjKV6po', 'default_content' => 'https://www.youtube.com/embed/4L49IjKV6po', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);


        StaticContent::create(['page' => 'About Us',  'item' => 'Top Picture', 'type' => 'image',
            'content' => 'http://lyderis.eu/wp-content/uploads/2011/05/junior-achievement.jpg', 'default_content' => 'http://lyderis.eu/wp-content/uploads/2011/05/junior-achievement.jpg', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Purpose', 'type' => 'text',
            'content' => 'Junior Achievement\'s Purpose is to inspire and prepare young people to succeed in a global economy.', 'default_content' => 'Junior Achievement\'s Purpose is to inspire and prepare young people to succeed in a global economy.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Who We Are', 'type' => 'text',
            'content' => 'Junior Achievement is the world\'s largest organization dedicated to giving children the knowledge and skills they need to own their economic success, plan for their future, and make smart academic and economic choices. Junior Achievement programs are delivered by business and community volunteers and provide relevant, hands-on experiences that give students from kindergarten through high school the knowledge and skills in financial literacy, work readiness and entrepreneurship. Founded in 1919, Junior Achievement has operated programs in Omaha since 1962.', 'default_content' => 'Junior Achievement is the world\'s largest organization dedicated to giving children the knowledge and skills they need to own their economic success, plan for their future, and make smart academic and economic choices. Junior Achievement programs are delivered by business and community volunteers and provide relevant, hands-on experiences that give students from kindergarten through high school the knowledge and skills in financial literacy, work readiness and entrepreneurship. Founded in 1919, Junior Achievement has operated programs in Omaha since 1962.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Core Value 1', 'type' => 'text', 'content' => 'Belief in the boundless potential of young people', 'default_content' => 'Belief in the boundless potential of young people', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Core Value 2', 'type' => 'text', 'content' => 'Commitment to the principles of market-based economics and entrepreneurship', 'default_content' => 'Commitment to the principles of market-based economics and entrepreneurship', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Core Value 3', 'type' => 'text', 'content' => 'Passion for what we do and honesty, integrity, and excellence in how we do it', 'default_content' => 'Passion for what we do and honesty, integrity, and excellence in how we do it', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Core Value 4', 'type' => 'text', 'content' => 'Respect for the talents, creativity, perspectives, and backgrounds of all individuals', 'default_content' => 'Respect for the talents, creativity, perspectives, and backgrounds of all individuals', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Core Value 5', 'type' => 'text', 'content' => 'Belief in the power of partnership and collaboration', 'default_content' => 'Belief in the power of partnership and collaboration', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Core Value 6', 'type' => 'text', 'content' => 'Conviction in the educational and motivational impact of relevant, hands-on learning', 'default_content' => 'Conviction in the educational and motivational impact of relevant, hands-on learning', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'What Is Junior Achievement USA', 'type' => 'text', 'content' => 'We are the nation\'s largest organization dedicated to giving young people the knowledge and skills they need to own their economic success, plan for their futures, and make smart academic and economic choices. Junior Achievement\'s programs—in the core content areas of work readiness, entrepreneurship and financial literacy—ignite the spark in young people to experience and realize the opportunities and realities of work and life in the 21st century.', 'default_content' => 'We are the nation\'s largest organization dedicated to giving young people the knowledge and skills they need to own their economic success, plan for their futures, and make smart academic and economic choices. Junior Achievement\'s programs—in the core content areas of work readiness, entrepreneurship and financial literacy—ignite the spark in young people to experience and realize the opportunities and realities of work and life in the 21st century.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Proven Success', 'type' => 'text', 'content' => 'Junior Achievement is one of a few nonprofits to use independent, third-party evaluators to gauge the impact of its programs. Since 1993, independent evaluators have conducted studies on Junior Achievement\'s effectiveness. Findings prove that Junior Achievement has a positive impact in a number of critical areas. We invite you to read the Programs Evaluation Results.', 'default_content' => 'Junior Achievement is one of a few nonprofits to use independent, third-party evaluators to gauge the impact of its programs. Since 1993, independent evaluators have conducted studies on Junior Achievement\'s effectiveness. Findings prove that Junior Achievement has a positive impact in a number of critical areas. We invite you to read the Programs Evaluation Results.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Purpose', 'type' => 'text', 'content' => 'Junior Achievement\'s purpose is to inspire and prepare young people to succeed in a global economy.', 'default_content' => 'Junior Achievement\'s purpose is to inspire and prepare young people to succeed in a global economy.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Program Reach', 'type' => 'text', 'content' => 'Junior Achievement USA reaches more than 4.6 million students per year in 201,444 classrooms and after-school locations. Junior Achievement programs are taught by volunteers in inner cities, suburbs, and rural areas throughout the United States, by 112 Area Offices in all 50 states.', 'default_content' => 'Junior Achievement USA reaches more than 4.6 million students per year in 201,444 classrooms and after-school locations. Junior Achievement programs are taught by volunteers in inner cities, suburbs, and rural areas throughout the United States, by 112 Area Offices in all 50 states.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'A Brief History', 'type' => 'text', 'content' => 'Junior Achievement was founded in 1919 by Theodore Vail, president of American Telephone & Telegraph; Horace Moses, president of Strathmore Paper Co.; and Senator Murray Crane of Massachusetts. Its first program, Junior Achievement Company Program®, was offered to high school students on an after-school basis. In 1975, the organization entered the classroom with the introduction of Project Business for the middle grades. Over the last 39 years, Junior Achievement has expanded its activities and broadened its scope to include in-school and after-school students.', 'default_content' => 'Junior Achievement was founded in 1919 by Theodore Vail, president of American Telephone & Telegraph; Horace Moses, president of Strathmore Paper Co.; and Senator Murray Crane of Massachusetts. Its first program, Junior Achievement Company Program®, was offered to high school students on an after-school basis. In 1975, the organization entered the classroom with the introduction of Project Business for the middle grades. Over the last 39 years, Junior Achievement has expanded its activities and broadened its scope to include in-school and after-school students.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Leadership', 'type' => 'text', 'content' => 'Ms. Julie Monaco, Global Head of Citi\'s Public Sector Group in the Corporate and Investment Banking division of Citi\'s Institutional Clients Group, is chairwoman of the Junior Achievement USA board of directors. Jack E. Kosakowski is the president and chief executive officer of Junior Achievement. Junior Achievement USA board members represent a wide range of businesses and academic institutions around the world. In addition, approximately 4,400 board members lead Junior Achievement Area Offices around the United States.', 'default_content' => 'Ms. Julie Monaco, Global Head of Citi\'s Public Sector Group in the Corporate and Investment Banking division of Citi\'s Institutional Clients Group, is chairwoman of the Junior Achievement USA board of directors. Jack E. Kosakowski is the president and chief executive officer of Junior Achievement. Junior Achievement USA board members represent a wide range of businesses and academic institutions around the world. In addition, approximately 4,400 board members lead Junior Achievement Area Offices around the United States.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Organization Overview', 'type' => 'text', 'content' => 'Junior Achievement USA is headquartered in Colorado Springs, Colorado, and provides strategic direction, leadership, and support to approximately 1,500 employees throughout the United States. Local volunteer boards of directors comprised of business, education, and civic leaders set the policy and direction for each local office.', 'default_content' => 'Junior Achievement USA is headquartered in Colorado Springs, Colorado, and provides strategic direction, leadership, and support to approximately 1,500 employees throughout the United States. Local volunteer boards of directors comprised of business, education, and civic leaders set the policy and direction for each local office.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'About Us',  'item' => 'Volunteers', 'type' => 'text', 'content' => 'Junior Achievement\'s 218,896 classroom volunteers come from all walks of life, including: business people, college students, parents and retirees. These dedicated individuals are the backbone of our organization.', 'default_content' => 'Junior Achievement\'s 218,896 classroom volunteers come from all walks of life, including: business people, college students, parents and retirees. These dedicated individuals are the backbone of our organization.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Get Involved',  'item' => 'Corporate Donor', 'type' => 'text', 'content' => 'Your corporation can support the growing need for youth development by helping today\'s students with the critical skills and the character necessary to succeed in your 21st century workplace.', 'default_content' => 'Your corporation can support the growing need for youth development by helping today\'s students with the critical skills and the character necessary to succeed in your 21st century workplace.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Get Involved',  'item' => 'Individual Donor', 'type' => 'text', 'content' => 'Not affiliated with a corporation partnered with Junior Achievement? You can make a donation directly to Junior Achievement of Midlands!', 'default_content' => 'Not affiliated with a corporation partnered with Junior Achievement? You can make a donation directly to Junior Achievement of Midlands!', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Get Involved',  'item' => 'Corporate Volunteer', 'type' => 'text', 'content' => 'By volunteering for Junior Achievement through your organization, you can be in the classroom during work hours and you can share your experience and inspire young people to pursue their dreams.', 'default_content' => 'By volunteering for Junior Achievement through your organization, you can be in the classroom during work hours and you can share your experience and inspire young people to pursue their dreams.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Get Involved',  'item' => 'Individual Volunteer', 'type' => 'text', 'content' => 'Not affiliated with a corporation partnered with Junior Achievement? You can volunteer directly with Junior Achievement of Midlands!', 'default_content' => 'Not affiliated with a corporation partnered with Junior Achievement? You can volunteer directly with Junior Achievement of Midlands!', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Get Involved',  'item' => 'Educator', 'type' => 'text', 'content' => 'Quality volunteers from the community come into your classroom to deliver proven, hands-on programming that inspires students to understand the opportunities provided by education.', 'default_content' => 'Quality volunteers from the community come into your classroom to deliver proven, hands-on programming that inspires students to understand the opportunities provided by education.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Get Involved',  'item' => 'Learn More About Junior Achievement Programs', 'type' => 'text', 'content' => 'Not an Educator? Find out how you can get Junior Achievement programs into your local community!', 'default_content' => 'Not an Educator? Find out how you can get Junior Achievement programs into your local community!', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Educators',  'item' => 'Top Picture', 'type' => 'image', 'content' => '../images/EducatorsPage.jpg', 'default_content' => '../images/EducatorsPage.jpg', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Educators',  'item' => 'Top Description', 'type' => 'text', 'content' => 'Junior Achievement brings quality volunteers from the community into your classroom to deliver proven, hands-on programming on financial literacy, work readiness, and entrepreneurship that inspires students to understand the opportunities provided by education.', 'default_content' => 'Junior Achievement brings quality volunteers from the community into your classroom to deliver proven, hands-on programming on financial literacy, work readiness, and entrepreneurship that inspires students to understand the opportunities provided by education.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Educators',  'item' => 'Importance', 'type' => 'text', 'content' => 'Junior Achievement reinforces the value of an education. Evaluations conducted by an independent research firm showed that an average of eight out of 10 high school students reported that Junior Achievement programs helped reinforce the importance of staying in school. In longitudinal studies, Junior Achievement students were significantly more likely than their peers to believe that they would graduate from high school, pursue post-secondary education and graduate from college.', 'default_content' => 'Junior Achievement reinforces the value of an education. Evaluations conducted by an independent research firm showed that an average of eight out of 10 high school students reported that Junior Achievement programs helped reinforce the importance of staying in school. In longitudinal studies, Junior Achievement students were significantly more likely than their peers to believe that they would graduate from high school, pursue post-secondary education and graduate from college.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Educators',  'item' => 'Preparation', 'type' => 'text', 'content' => 'Ninety-five percent of teachers report that students who participate in Junior Achievement have a better understanding of how the real world operates, and nine out of 10 teachers and volunteers agree that Junior Achievement programs connect what is learned in the classroom to the outside world.', 'default_content' => 'Ninety-five percent of teachers report that students who participate in Junior Achievement have a better understanding of how the real world operates, and nine out of 10 teachers and volunteers agree that Junior Achievement programs connect what is learned in the classroom to the outside world.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Educators',  'item' => 'Recommended', 'type' => 'text', 'content' => 'Ninety-six percent of teachers agreed or strongly agreed that they would recommend Junior Achievement to a colleague or friend.', 'default_content' => 'Ninety-six percent of teachers agreed or strongly agreed that they would recommend Junior Achievement to a colleague or friend.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Educators',  'item' => 'Sign Up', 'type' => 'text', 'content' => 'Interesting, right? Would you like to have Junior Achievement in your classroom? Just reach out to Junior Achievement of Midlands to sign up.', 'default_content' => 'Interesting, right? Would you like to have Junior Achievement in your classroom? Just reach out to Junior Achievement of Midlands to sign up.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Educators',  'item' => 'Bottom Video', 'type' => 'video', 'content' => 'https://www.youtube.com/embed/XZLeBFNIUVo', 'default_content' => 'https://www.youtube.com/embed/XZLeBFNIUVo', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Volunteers',  'item' => 'Top Picture', 'type' => 'text', 'content' => 'https://www.juniorachievement.org/documents/20009/1817412/volunteer-ja-crop.jpg', 'default_content' => 'https://www.juniorachievement.org/documents/20009/1817412/volunteer-ja-crop.jpg', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Volunteers',  'item' => 'Top Description', 'type' => 'text', 'content' => 'A want versus a need. How to balance a checkbook. Don\'t you wish that someone had taught you those things as you were growing up? Now there is someone. YOU. All we need is your enthusiasm, life experience, and a willingness to teach children about how you took chances and shoot for the stars. Junior Achievement provides the training, curriculum, and a classroom ready to meet you!', 'default_content' => 'A want versus a need. How to balance a checkbook. Don\'t you wish that someone had taught you those things as you were growing up? Now there is someone. YOU. All we need is your enthusiasm, life experience, and a willingness to teach children about how you took chances and shoot for the stars. Junior Achievement provides the training, curriculum, and a classroom ready to meet you!', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Volunteers',  'item' => 'Make A Difference', 'type' => 'text', 'content' => 'By being a Junior Achievement volunteer and sharing your personal and professional experiences and skills with students from our community, you help them make the connection between what they are learning in school and what they will need to succeed in work and life.', 'default_content' => 'By being a Junior Achievement volunteer and sharing your personal and professional experiences and skills with students from our community, you help them make the connection between what they are learning in school and what they will need to succeed in work and life.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Volunteers',  'item' => 'Inspire', 'type' => 'text', 'content' => 'For a time investment of only an hour a week, you may be the difference between a young person just making ends meet or getting a more fulfilling career and life.', 'default_content' => 'For a time investment of only an hour a week, you may be the difference between a young person just making ends meet or getting a more fulfilling career and life.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Volunteers',  'item' => 'Experience', 'type' => 'text', 'content' => 'Junior Achievement gives you an opportunity through your employer\'s volunteer program (or on your own) to impact young people in our community in a positive way with simple to implement programs on financial literacy, work readiness, and entrepreneurship. This will empower young people to own their economic success.', 'default_content' => 'Junior Achievement gives you an opportunity through your employer\'s volunteer program (or on your own) to impact young people in our community in a positive way with simple to implement programs on financial literacy, work readiness, and entrepreneurship. This will empower young people to own their economic success.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Volunteers',  'item' => 'Sign Up', 'type' => 'text', 'content' => 'Interesting, right? Would you like to engage with Junior Achievement? Just reach out to Junior Achievement of Midlands to sign up.', 'default_content' => 'Interesting, right? Would you like to engage with Junior Achievement? Just reach out to Junior Achievement of Midlands to sign up.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Volunteers',  'item' => 'Bottom Video', 'type' => 'video', 'content' => 'https://www.youtube.com/embed/HNUpbr7NeL0', 'default_content' => 'https://www.youtube.com/embed/HNUpbr7NeL0', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Donors',  'item' => 'Top Picture', 'type' => 'picture', 'content' => 'https://www.juniorachievement.org/documents/20009/1817412/about-pg.png', 'default_content' => 'https://www.juniorachievement.org/documents/20009/1817412/about-pg.png', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Donors',  'item' => 'Top Description', 'type' => 'text', 'content' => 'Is your company looking to partner with an organization that makes a difference in the lives of youth in your community? Junior Achievement provides programs that are delivered to students in the classroom. Junior Achievement programs are developed with a focus on several critically needed areas; STEM, Building Leadership Skills, Uplifting At-Risk Communities, Work Readiness and Soft Skills, Business Ethics, College Readiness, Career and Technical Education (CTE), Industry Focus (Manufacturing/Health), and Financial Literacy.', 'default_content' => 'Is your company looking to partner with an organization that makes a difference in the lives of youth in your community? Junior Achievement provides programs that are delivered to students in the classroom. Junior Achievement programs are developed with a focus on several critically needed areas; STEM, Building Leadership Skills, Uplifting At-Risk Communities, Work Readiness and Soft Skills, Business Ethics, College Readiness, Career and Technical Education (CTE), Industry Focus (Manufacturing/Health), and Financial Literacy.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Donors',  'item' => 'Your Donation', 'type' => 'text', 'content' => 'Junior Achievement inspires and prepares young people to succeed in the global economy. By partnering with Junior Achievement, you will empower young people to own their economic success.', 'default_content' => 'Junior Achievement inspires and prepares young people to succeed in the global economy. By partnering with Junior Achievement, you will empower young people to own their economic success.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Donors',  'item' => 'Workforce', 'type' => 'text', 'content' => 'Junior Achievement will help you develop leaders with the critical skills and the character necessary to succeed in our 21st century workplace.', 'default_content' => 'Junior Achievement will help you develop leaders with the critical skills and the character necessary to succeed in our 21st century workplace.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Donors',  'item' => 'Employees', 'type' => 'text', 'content' => 'Junior Achievement will empower your employees with quality, skills-based volunteering experiences in our community using proven programs that change young peoples\' lives.', 'default_content' => 'Junior Achievement will empower your employees with quality, skills-based volunteering experiences in our community using proven programs that change young peoples\' lives.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Donors',  'item' => 'Donate Now', 'type' => 'text', 'content' => 'Every single dollar makes a difference. Donating to Junior Achievement will help to expand Junior Achievement\'s enriching curriculum to benefit more students.', 'default_content' => 'Every single dollar makes a difference. Donating to Junior Achievement will help to expand Junior Achievement\'s enriching curriculum to benefit more students.', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Donors',  'item' => 'Bottom Video', 'type' => 'video', 'content' => 'https://www.youtube.com/embed/nTmryDIQq6s', 'default_content' => 'https://www.youtube.com/embed/nTmryDIQq6s', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Map Location', 'type' => 'text', 'content' => 'https://www.google.com/maps/embed/v1/place?q=Junior+Achievement-Midlands,+West+Maple+Road,+Omaha,+NE,+United+States&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU', 'default_content' => 'https://www.google.com/maps/embed/v1/place?q=Junior+Achievement-Midlands,+West+Maple+Road,+Omaha,+NE,+United+States&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 1 Name', 'type' => 'text', 'content' => 'John Healey', 'default_content' => 'John Healey', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 1 Title', 'type' => 'text', 'content' => 'President', 'default_content' => 'President', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 1 Phone', 'type' => 'text', 'content' => '402-333-6410 x 203', 'default_content' => '402-333-6410 x 203', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 2 Name', 'type' => 'text', 'content' => 'Roxanne Mulvey', 'default_content' => 'Roxanne Mulvey', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 2 Title', 'type' => 'text', 'content' => 'Elementary School Program', 'default_content' => 'Elementary School Program', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 2 Phone', 'type' => 'text', 'content' => '402-333-6410 x 202', 'default_content' => '402-333-6410 x 202', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 3 Name', 'type' => 'text', 'content' => 'Jamie Hermanson', 'default_content' => 'Jamie Hermanson', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 3 Title', 'type' => 'text', 'content' => 'Middle/High School Programs', 'default_content' => 'Middle/High School Programs', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);

        StaticContent::create(['page' => 'Contact Us',  'item' => 'Person 3 Phone', 'type' => 'text', 'content' => '402-333-6410 x 201', 'default_content' => '402-333-6410 x 201', 'updated_by' => 'System', 'created_at' => date_create(), 'updated_at' => date_create()]);


    }
}



    